.clang-format
.github/workflows/clang-format.yml
.github/workflows/ubuntu_pull_request.yml
.github/workflows/ubuntu_push.yml

Added CI for ubuntu and clang-format-check

#6 Added first CI try

---

README.md
doc/DEPENDENCIES.md
doc/INSTALL.md
doc/STYLEGUIDE.md
doc/TARGETS.md

Add documentation

---

.github/workflows/documentation.yml
_config.yml
doc/doxygen/Doxyfile
doc/doxygen/doxygen-awesome-darkmode-toggle.js
doc/doxygen/doxygen-awesome.css
doc/doxygen/footer.html
doc/doxygen/header.html

In this PR changed doxygen documentation template to doxygen awesome

Kononovk dev doxygen

---

.github/pull_request_template.md
.github/workflows/coverage.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/sanitizer.yml
.github/workflows/windows.yml
include/yaclib/algo/detail/when_all_impl.hpp
include/yaclib/algo/detail/when_any_impl.hpp
include/yaclib/algo/detail/when_impl.hpp
include/yaclib/algo/when_all.hpp
include/yaclib/algo/when_any.hpp
include/yaclib/async/detail/base_core.hpp
include/yaclib/async/detail/future_impl.hpp
include/yaclib/async/detail/result_core.hpp
src/algo/CMakeLists.txt
src/async/base_core.cpp

* Try to fix CI
* Fix: Subscribe Core don't need non-trivial Set, store Result<V, E> and Future unwrapping
* Replace atomic reference counter add by ctor

Fix clang CI and some performance improvements

---

.github/pull_request_template.md

Labels instead of emoji in the PR description

Labels instead of emoji in the PR description

---

include/yaclib/include/yaclib/coroutine/detail/config.hpp

Remove file that was generated by CMake

Remove redundant header

---

.github/workflows/coverage.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/sanitizer.yml
include/yaclib/algo/detail/wait_impl.hpp
include/yaclib/async/future.hpp
src/algo/wait_impl.cpp
src/log_error.cpp
src/log_info.cpp
test/unit/async/make_future.cpp

* [Remove unnecessary detail::](https://github.com/YACLib/YACLib/commit/2fbd72637c98eaf699b706e34f5c1a6c35dddfe3)
* [Make exception, ready, stopped future and test it](https://github.com/YACLib/YACLib/commit/28564831bea83893d1d15b3952928e25c127493c)
* [Some fixes for coverage](https://github.com/YACLib/YACLib/commit/2b4effe08b676653bc1ba66c27081a4fd66adc68)

Small fixes

---

.github/workflows/coverage.yml

Some fixes for coverage

---

include/yaclib/async/contract.hpp
include/yaclib/async/detail/core.hpp
include/yaclib/async/detail/future_impl.hpp
include/yaclib/async/detail/result_core.hpp
include/yaclib/async/future.hpp
include/yaclib/executor/detail/unique_task.hpp
include/yaclib/executor/executor.hpp
include/yaclib/executor/submit.hpp
include/yaclib/executor/thread_factory.hpp
include/yaclib/util/detail/safe_call.hpp
include/yaclib/util/detail/shared_func.hpp
include/yaclib/util/func.hpp
src/async/base_core.cpp
src/executor/inline.cpp
src/executor/strand.cpp
src/executor/thread_pool.cpp
src/util/CMakeLists.txt
test/CMakeLists.txt
test/unit/async/future.cpp
test/unit/executor/task.cpp
test/unit/not_implemented.cpp

~~Please use labels for this PR~~
~~Please describe the changes in this PR for reviewers~~

Remove unnecessary IncRef also make Submit unconditional

---

.github/workflows/coverage.yml
.github/workflows/format.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/sanitizer.yml
.github/workflows/windows.yml
test/unit/algo/wait_group.cpp

Make CI better

---

README.md
doc/install.md
doc/yaclib_std.md

Fixing typos in the documentation, including making one of the examples work.
Documentation-only changes.

fix small documentation issues

---

include/yaclib/algo/detail/base_core.hpp
include/yaclib/algo/detail/core.hpp
include/yaclib/algo/detail/inline_core.hpp
include/yaclib/algo/detail/result_core.hpp
include/yaclib/async/contract.hpp
include/yaclib/async/detail/future_impl.hpp
include/yaclib/async/detail/when_all_impl.hpp
include/yaclib/async/detail/when_any_impl.hpp
include/yaclib/async/future.hpp
include/yaclib/coro/detail/promise_type.hpp
include/yaclib/lazy/detail/task_impl.hpp
include/yaclib/lazy/make.hpp
include/yaclib/lazy/schedule.hpp
include/yaclib/lazy/task.hpp
src/algo/base_core.cpp
src/lazy/task_impl.cpp
test/unit/async/core_size.cpp
test/unit/async/future_inline.cpp
test/unit/async/make_future.cpp
test/unit/async/make_task.cpp
test/unit/async/stress.cpp
test/unit/async/task.cpp
test/unit/coro/await_group.cpp

Also make first step to current executor in coroutines

Remove caller overhead

---

include/yaclib/util/detail/atomic_event.hpp
src/config.hpp.in

~~Please use labels for this PR~~
~~Please describe the changes in this PR for reviewers~~

Enable platform wait for more cases

---

.github/workflows/sanitizer.yml
include/yaclib/async/future.hpp
include/yaclib/async/promise.hpp
include/yaclib/fwd.hpp
include/yaclib/lazy/task.hpp
include/yaclib/util/result.hpp

Fix forward declaration usability and CI

---

include/yaclib/async/contract.hpp
include/yaclib/async/detail/when_all_impl.hpp
include/yaclib/async/make.hpp
include/yaclib/async/when_all.hpp
include/yaclib/lazy/make.hpp
include/yaclib/util/result.hpp
test/unit/algo/when_all.cpp
test/unit/async/make_future.cpp
test/unit/async/make_task.cpp

* Make Future/Task now can works with const or lvalue
* WhenAll now support WhenPolicy::None
* Fix missing pragma once in yaclib/async/contract.hpp

Make it better

---

include/yaclib/algo/detail/core.hpp
include/yaclib/util/result.hpp
test/unit/async/future.cpp
test/unit/async/future_inline.cpp
test/unit/util/result.cpp

* Make destroy async callback after return value
* Add restrictions for Result getters
~~Please use labels for this PR~~
~~Please describe the changes in this PR for reviewers~~

Few improvements

---

cmake/yaclib_flags.cmake
include/yaclib/algo/detail/core.hpp
include/yaclib/algo/detail/func_core.hpp
include/yaclib/algo/detail/promise_core.hpp
include/yaclib/async/detail/when_impl.hpp
include/yaclib/async/run.hpp
include/yaclib/async/when_all.hpp
include/yaclib/async/when_any.hpp
include/yaclib/lazy/detail/task_impl.hpp
include/yaclib/lazy/schedule.hpp
src/lazy/task_impl.cpp
test/unit/async/future.cpp
test/util/async_suite.hpp

* Add AsyncContract
* Add LazyContract
* Fix few issues

Add Async/Lazy Contract

---

test/util/async_suite.hpp
test/util/error_suite.hpp

Add missing pragma once in test headers

---

CMakeLists.txt
src/CMakeLists.txt

Add YACLIB_INSTALL option and determine default cxx standard if YACLIB_CXX_STANDARD wasn't specified

---

.gitignore
doc/install.md
include/yaclib/coro/detail/await_on_awaiter.hpp
test/unit/coro/await.cpp

Added Await overload with IExecutor (#193)

---

include/yaclib/fault/detail/fiber/default_allocator.hpp
src/config.hpp.in
test/unit/coro/await_group.cpp
test/unit/coro/await_group_stress.cpp
test/util/helpers.hpp

Make test more reliable

---

.githooks/pre-commit

Fix pre-commit for submodules

---

.github/workflows/coverage.yml
.github/workflows/linux.yml
.github/workflows/sanitizer.yml

Add new compilers to CI
